### ISSUE TITLE
How to use Minimongo, Please share any reference?

### ISSUE THREAD

**Issue by technicalbirdVayuz** [harryadel/blastjs#5]

**Comment by technicalbirdVayuz** [comment]
Getting Error as, Minimongo.LocalCollection is not a constructor, Trying  with

var User = new Minimongo.LocalCollection("data")

**Comment by jamesgibson14** [comment]
Try `new LocalCollection(null)` or  `new LocalCollection('data')`  that is what I use.

**Comment by technicalbirdVayuz** [comment]
Hi @jamesgibson14 ,

Does this package provide reactivity? I have tried it but its only adds in local collection only, whenever I want to retrieve the data using the helper function, getting a blank array.

**Comment by jamesgibson14** [comment]
Yes it does, in your helper just do something like:
```javascript
getUser( userId ){
  return User.findOne({_id: userId})
}
```

**Comment by technicalbirdVayuz** [comment]
Attaching the code, please have a look


```
var User = new LocalCollection("data")

Template.listingLayout.onCreated(function(){
  User.insert({"title":"Hello"})
});

Template.listingLayout.helpers({
  data: function () {
    return User.find({}).fetch();
  },
});

document.addEventListener("dataReceived", function (data) {
  User.insert({ title: "New Data" });
 });
```


Dispatching event from the client side, but helper function returns only 1 document. Also, I am using it with webpack

**Comment by technicalbirdVayuz** [comment]
Changed to  `User.find({}) `only, its working now, Thanks!

**Comment by harryadel** [comment]
Thank you @jamesgibson14 for your effort <3

**Comment by jamesgibson14** [comment]
No problem, I am glad @technicalbirdVayuz figured it out.
